# Use this template to override the name, hostname, and network name without modifying git status.

# Copy this file to compose.naming.override.yaml and set the name:
#   cp .devcontainer/docker_compose_configuration_customizations/naming/compose.naming.override.example.yaml .devcontainer/docker_compose_configuration_customizations/naming/compose.naming.override.yaml

name: "super_projects"
services:
  devcontainer:
    hostname: "super_projects"
    networks:
      - super_projects_default
  localhost_forward_proxy:
    networks:
      - super_projects_default
networks:
  super_projects_default:
    name: "super_projects_default"
